language: node_js

branches:
  only:
    - master

install:
  - npm install

node_js:
  - "10.18"
  - "12.13"
  - "14.15"

script:
  - npm run lint


jobs:
  include:
    - stage: build-and-deploy
      node_js: "10.18"
      script:
        - npm run build && npm run semantic-release

stages:
  - Test
  - name: build-and-deploy
    if: false
